In [1]:
import cvxpy as cp

In [44]:
x = cp.Variable((2,4),integer=True)
obj = cp.Maximize(-5*x[0,0]-10*x[1,0]-10*(x[0,1]+x[0,2]+x[0,3])-20*(x[1,1]+x[1,2]+x[1,3])+20000
                 +2.5*(x[0,0]-98+x[0,1]-265+20+x[0,2]-115+x[0,3]-42)
                 +5*(x[1,0]-98+x[1,1]-231+20+x[1,2]-123+x[1,3]-38))
cons = [
    3*x[0,0]+2*x[1,0]<=1200,
    5*x[0,0]+10*x[1,0]<=10000,
    x[0,0]-98>=0,
    x[0,0]-98+x[0,1]-265+20>=0,
    x[0,0]-98+x[0,1]-265+20+x[0,2]-115>=0,
    x[0,0]-98+x[0,1]-265+20+x[0,2]-115+x[0,3]-42>=0,
    x[1,0]-98>=0,
    x[1,0]-98+x[1,1]-231+20>=0,
    x[1,0]-98+x[1,1]-231+20+x[1,2]-123>=0,
    x[1,0]-98+x[1,1]-231+20+x[1,2]-123+x[1,3]-38>=0,
    
    3*(x[0,0]-98+x[0,1])+2*(x[1,0]-98+x[1,1])<=1200,
    3*(x[0,0]-98+x[0,1]-265+20+x[0,2])+2*(x[1,0]-98+x[1,1]-231+20+x[1,2])<=1200,
    3*(x[0,0]-98+x[0,1]-265+20+x[0,2]-115+x[0,3])+2*(x[1,0]-98+x[1,1]-231+20+x[1,2]-123+x[1,3])<=1200,
    x>=0
    
]
prob = cp.Problem(obj,cons)
prob.solve(solver = 'GLPK_MI')

9800.0

In [41]:
x.value

array([[180., 163., 157.,   0.],
       [330.,   0., 140.,   0.]])

In [45]:
prob.value

9800.0

In [5]:
x = cp.Variable((2,4),integer=True)
obj = cp.Maximize(-5*x[0,0]-10*x[1,0]-10*(x[0,1]+x[0,2]+x[0,3])-20*(x[1,1]+x[1,2]+x[1,3])+22000
                 +2.5*(x[0,0]-156+x[0,1]-10-210-16+x[0,2]-10-69-10+x[0,3]-32)
                 +5*(x[1,0]-144+x[1,1]-14-192-12+x[1,2]-14-69-14+x[1,3]-24))
cons = [
    3*x[0,0]+2*x[1,0]<=1200,
    5*x[0,0]+10*x[1,0]<=10000,
    x[0,0]-156>=0,
    x[0,0]-156+x[0,1]-236>=0,
    x[0,0]-156+x[0,1]-236+x[0,2]-89>=0,
    x[0,0]-156+x[0,1]-236+x[0,2]-89+x[0,3]-32>=0,
    x[1,0]-144>=0,
    x[1,0]-144+x[1,1]-218>=0,
    x[1,0]-144+x[1,1]-218+x[1,2]-97>=0,
    x[1,0]-144+x[1,1]-218+x[1,2]-97+x[1,3]-24>=0,
    
    3*(x[0,0]-156+x[0,1])+2*(x[1,0]-144+x[1,1])<=1200,
    3*(x[0,0]-156+x[0,1]-236+x[0,2])+2*(x[1,0]-144+x[1,1]-218+x[1,2])<=1200,
    3*(x[0,0]-156+x[0,1]-236+x[0,2]-89+x[0,3])+2*(x[1,0]-144+x[1,1]-218+x[1,2]-97+x[1,3])<=1200,
    x>=0
    
]
prob = cp.Problem(obj,cons)
prob.solve(solver = 'GLPK_MI')

11650.0

In [6]:
x.value

array([[156., 252., 105.,   0.],
       [366.,   0., 117.,   0.]])

In [46]:
import numpy as np
c=[
    [98,245,115,42],
    [98,211,123,38]
]
c = np.array(c)
c[0,0]

98

In [48]:
x = cp.Variable((2,4),integer=True)
obj = cp.Maximize(-5*x[0,0]-10*x[1,0]-10*(x[0,1]+x[0,2]+x[0,3])-20*(x[1,1]+x[1,2]+x[1,3])+20000
                 +2.5*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]+x[0,3]-c[0,3])
                 +5*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]+x[1,3]-c[1,3]))
cons = [
    3*x[0,0]+2*x[1,0]<=1200,
    5*x[0,0]+10*x[1,0]<=10000,
    x[0,0]-c[0,0]>=0,
    x[0,0]-c[0,0]+x[0,1]-c[0,1]>=0,
    x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]>=0,
    x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]+x[0,3]-c[0,3]>=0,
    x[1,0]-c[1,0]>=0,
    x[1,0]-c[1,0]+x[1,1]-c[1,1]>=0,
    x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]>=0,
    x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]+x[1,3]-c[1,3]>=0,
    
    3*(x[0,0]-c[0,0]+x[0,1])+2*(x[1,0]-c[1,0]+x[1,1])<=1200,
    3*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2])+2*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2])<=1200,
    3*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]+x[0,3])+2*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]+x[1,3])<=1200,
    x>=0
    
]
prob = cp.Problem(obj,cons)
prob.solve(solver = 'GLPK_MI')

9800.0

In [35]:
import numpy as np
c=[
    #case1:5，8 11955 2
    #[114+117+16,16+20+16+162+10,32],
    #[110+105+12,12+20+12+168+14,24]
    #case2:8，5 11955 2
    #[140,16+219+10,26+99+21],
    #[132,12+189+14,26+111+24]
    #case3:9, 4 12460 2
    #[156,10+210+16,10+84+32],
    #[144,14+192+12,14+90+24]
    #case6:4,6,4 12195
    #[114+93+16,32+138+16,10+84+32],
    #[110+87+12,24+138+12,14+90+24]
    #case4:5,9 12345 2
    #[114+117+16,16+207+16,36],
    #[110+105+12,12+207+12,40]
    #case5:7,3 9800 1
    #[98,32+171+10+32,20+69+68],
    #[98,24+153+10+24,28+69+64]
    #case12:7 10430
    #[98,32+171+10+32,36],
    #[98,24+153+10+24,40]
    #case shang1 9
    #[130+10,16+210+10,26+10+16],
    #[122+10,12+192+14,26+10+12]
    #case xia1 9
    #[156,10+210+16,10+10+16],
    #[144,14+192+12,14+10+12]
    #new 2 , 9 11105
    #[156+39+16,16+207+16,20],
    #[144+39+12,12+207+12,28]
    #new 2,9,1
    #[156+39+16,16+207+16,10+15+32],
    #[144+39+12,12+207+12,14+21+24]
    #case14 2 7 5 12580
    #[114+54+16,26+171+10,16+99+32],
    #[110+48+12,26+153+14,12+111+24]
    #case14 4 6 4
    #[114+93+16,32+123+10,16+99+32],
    #[110+87+12,24+117+14,12+111+24]
    #case14 6,7 12730
    [130,10+16+147+16,26+138+32],
    [122,10+12+135+12,26+150+24]
    #case1 7 10470
    #[98,243,36],
    #[98,211,40]
]
c = np.array(c)
c[0,0]
m=[[6000,7000]]
m=np.array(m)
m[0,0]

6000

In [36]:
x = cp.Variable((2,3),integer=True)
obj = cp.Maximize(10000-5*x[0,0]-10*x[1,0]-10*(x[0,1]+x[0,2])-20*(x[1,1]+x[1,2])+m[0,0]+m[0,1]
                 +2.5*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2])
                 +5*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]))
cons = [
    3*x[0,0]+2*x[1,0]<=1200,
    5*x[0,0]+10*x[1,0]<=10000,
    x[0,0]-c[0,0]>=0,
    x[0,0]-c[0,0]+x[0,1]-c[0,1]>=0,
    x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]>=0,
    #x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]+x[0,3]-c[0,3]>=0,
    x[1,0]-c[1,0]>=0,
    x[1,0]-c[1,0]+x[1,1]-c[1,1]>=0,
    x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]>=0,
    #x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]+x[1,3]-c[1,3]>=0,
    
    3*(x[0,0]-c[0,0]+x[0,1])+2*(x[1,0]-c[1,0]+x[1,1])<=1200,
    3*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2])+2*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2])<=1200,
    #3*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]+x[0,3])+2*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]+x[1,3])<=1200,
    x>=0,
    #case1
    #10*x[0,1]+20*x[1,1]<=10000-5*x[0,0]+10*x[1,0],
    #10*x[0,2]+20*x[1,2]<=10000-5*x[0,0]+10*x[1,0]-10*x[0,1]+20*x[1,1]+m[0,0]
]
prob = cp.Problem(obj,cons)
prob.solve(solver = 'GLPK_MI')

12730.0

In [37]:
x.value

array([[130., 211., 174.],
       [405.,   0.,  86.]])

In [81]:
import numpy as np
c=[
    #shang 1 5个 9715
    #[114+117+16,16+20+32],
    #[110+105+12,12+20+24]
    #shang 1 9个 inf 要补给
    #[130+10,16+210+10+26+10+16],
    #[122+10,12+192+14+26+10+12]
    #xxia 1 9 
    [156,10+210+26],
    [144,14+192+26]
]
c = np.array(c)
m=[[9000]]
m=np.array(m)
m[0,0]

9000

In [82]:
x = cp.Variable((2,2),integer=True)
obj = cp.Maximize(10000-5*x[0,0]-10*x[1,0]-10*(x[0,1])-20*(x[1,1])+m[0,0]
                 +2.5*(x[0,0]-c[0,0]+x[0,1]-c[0,1])
                 +5*(x[1,0]-c[1,0]+x[1,1]-c[1,1]))
cons = [
    3*x[0,0]+2*x[1,0]<=1200,
    5*x[0,0]+10*x[1,0]<=10000,
    x[0,0]-c[0,0]>=0,
    x[0,0]-c[0,0]+x[0,1]-c[0,1]>=0,
   # x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]>=0,
    #x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]+x[0,3]-c[0,3]>=0,
    x[1,0]-c[1,0]>=0,
    x[1,0]-c[1,0]+x[1,1]-c[1,1]>=0,
   # x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]>=0,
    #x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]+x[1,3]-c[1,3]>=0,
    
    3*(x[0,0]-c[0,0]+x[0,1])+2*(x[1,0]-c[1,0]+x[1,1])<=1200,
   # 3*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2])+2*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2])<=1200,
    #3*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]+x[0,3])+2*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]+x[1,3])<=1200,
    x>=0,
    #case1
    #10*x[0,1]+20*x[1,1]<=10000-5*x[0,0]+10*x[1,0],
    #10*x[0,2]+20*x[1,2]<=10000-5*x[0,0]+10*x[1,0]-10*x[0,1]+20*x[1,1]+m[0,0]
]
prob = cp.Problem(obj,cons)
prob.solve(solver = 'GLPK_MI')

-inf

In [ ]:
import cvxpy as cp
import numpy as np
c=[
    #case2: m=[9000,4000] 12460 
    #[156,10+210+16,10+84+32],
    #[144,14+192+12,14+90+24]

    #case2:m=[5000,9000] 12345 
    #[114+117+16,16+207+16,36],
    #[110+105+12,12+207+12,40]

    #case2 m=[6000,7000] 12730
    #[130,10+16+147+16,26+138+32],
    #[122,10+12+135+12,26+150+24]

    #case1 m=[7000,0] 10470
    #[98,243,36],
    #[98,211,40]
]
c = np.array(c)
m=[[9000,4000]]
m=np.array(m)

x = cp.Variable((2,3),integer=True)
obj = cp.Maximize(10000-5*x[0,0]-10*x[1,0]-10*(x[0,1]+x[0,2])-20*(x[1,1]+x[1,2])+m[0,0]+m[0,1]
                 +2.5*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2])
                 +5*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]))
cons = [
    3*x[0,0]+2*x[1,0]<=1200,
    5*x[0,0]+10*x[1,0]<=10000,
    x[0,0]-c[0,0]>=0,
    x[0,0]-c[0,0]+x[0,1]-c[0,1]>=0,
    x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2]-c[0,2]>=0,
    x[1,0]-c[1,0]>=0,
    x[1,0]-c[1,0]+x[1,1]-c[1,1]>=0,
    x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2]-c[1,2]>=0,
    3*(x[0,0]-c[0,0]+x[0,1])+2*(x[1,0]-c[1,0]+x[1,1])<=1200,
    3*(x[0,0]-c[0,0]+x[0,1]-c[0,1]+x[0,2])+2*(x[1,0]-c[1,0]+x[1,1]-c[1,1]+x[1,2])<=1200,
    x>=0
]
prob = cp.Problem(obj,cons)
prob.solve(solver = 'GLPK_MI')

print(x.value)
print(prob.value)